name: Bug Report
description: File a bug report
labels: ["bug"]
title: "[Bug] "
projects: ["Krealle/2"]
assignees:
  - Krealle
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to submit your bug report.
  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: What version of Cell_UnitFrames did this error happen on?
      placeholder: placeholder
    validations:
      required: true
  - type: dropdown
    id: wow-version
    attributes:
      label: World of Warcraft Version
      description: What World of Warcraft version did this happen on?
      options:
        - Retail
        - Retail PTR
        - Retail Beta
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
      placeholder: When selecting option zyx...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can this issue be reproduced?
      placeholder: 1. Select option xyz...
    validations:
      required: true
  - type: textarea
    id: bug-sack
    attributes:
      label: BugSack
      description: If relevant please provide the full BugSack report from the bug.
      render: bash
    validations:
      required: false
