name: Package and release

# we need to let GitHub know _when_ we want to release, which is only when we create a new tag.
on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:
      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v3

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@v2